import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import NoteCard from "../components/NoteCard";
import styles from "../styles/Home.module.scss";
import newNoteIcon from "../images/search.png";
import { notesState } from "../features/notesSlice";
import { useSelector, useDispatch } from "react-redux";
import { noteProp } from "../type";
import Link from "next/link";

const Home: NextPage = () => {
  const notes: noteProp[] = useSelector(notesState);
  console.log(notes);
  return (
    <div className={styles.container}>
      <Head>
        <title>My Notes</title>
        {/*
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />*/}
      </Head>
      <header  className={styles.h1}><h1>My notes</h1></header>
      <main className={styles.main}>
        <div>
          <Link href="/new-note">
            <img src={newNoteIcon.src} alt="new note?" />
          </Link>
        </div>
        {notes.length > 0 ? (
          notes.map((item, index) => (
            <div className={styles.notebox} key={index}>
              <NoteCard note={item} />
            </div>
          ))
        ) : (
          <div> Create your first note </div>
        )}
      </main>
      <footer className={styles.footer}>
        <a></a>
      </footer>
    </div>
  );
};

export default Home;
